### ISSUE TITLE
falsche Antworten

### ISSUE THREAD

**Issue by voltae** [voltae/educate_me#19]
bei der Seite teach werden falsche Antworten angezeigt. die Server Antwort beinhaltet aber die auf die korrekte Antwort.
`{"question":"Welcher ist der gr\u00f6\u00dfte Ozean der Erde?","answer":"Pazifischer Ozean","index":8,"alternatives":["Indischer Ozean","S\u00fcdlicher Ozean","Arktischer Ozean"]}`

**Comment by ic17b022** [comment]
fixed
