### ISSUE TITLE
Unterscheiden zwischen Üben und Test.

### ISSUE THREAD

**Issue by ic17b022** [voltae/educate_me#2]
IST: Momentan gibt Server immer ein Paktet mit 15 Fragen aus.
SOLL: ???

**Comment by voltae** [comment]
Test modul beginnt immer mit der 1. Frage, gibt die Fragen mittels Zufallsgenerator aus (durchmischt) und analysiert ob Frage richtig beantwortet wurde oder nicht. Modul führt Buch über die richtig eingegebenen Antworten und gibt am Ende die Anzahl der richtig beantworteten aus.
Antwortfelder (Buttons) sind mit Zufallsgenerator durchmischt.
