### ISSUE TITLE
Startpunkt definieren

### ISSUE THREAD

**Issue by ic17b022** [voltae/educate_me#3]
IST: Wir starten momentan beliebig. Das heißt, der Server hat noch keinen definierten Startpunkt, ab welchen er mit den genau 15 Fragen beginnt.
SOLL: ???

**Comment by voltae** [comment]
Soll: Im Modul Test (exam.html) beginnt der Test immer mit der ersten Frag. Zurückspringen an den Anfang ist während des Tests nicht möglich, erst wenn alle Fragen beantwortet wureden. Wiederholung möglich.
Abbruch des Tests jederzeit.
